// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanTechInvoicing.Data;

#nullable disable

namespace UrbanTechInvoicing.Migrations
{
    [DbContext(typeof(UrbanTechDbContext))]
    [Migration("20250602014114_FixInvoiceServicesRelationships")]
    partial class FixInvoiceServicesRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanTechInvoicing.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("4ba1b208-0e45-4fcf-9e38-4d41560236cf"),
                            EmailAddress = "customer1@email.com",
                            Name = "Robots Inc",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("de4e73b3-07cb-4c11-a09d-804c2f66db38"),
                            CustomerId = new Guid("4ba1b208-0e45-4fcf-9e38-4d41560236cf"),
                            DueDate = new DateTime(2025, 7, 2, 1, 41, 13, 234, DateTimeKind.Utc).AddTicks(3783),
                            InvoiceDate = new DateTime(2025, 6, 2, 1, 41, 13, 234, DateTimeKind.Utc).AddTicks(3782),
                            InvoiceNumber = "INV001",
                            InvoiceTotal = 1000.00m,
                            Status = "Unpaid"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InvoiceId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("InvoicePayments");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("de4e73b3-07cb-4c11-a09d-804c2f66db38"),
                            PaymentId = new Guid("07426956-44c3-4ec4-9c20-ecfcf28a9ca3"),
                            PaymentAmount = 1000.00m,
                            PaymentDate = new DateTime(2025, 6, 2, 1, 41, 13, 234, DateTimeKind.Utc).AddTicks(3948)
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InvoiceServices");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("07426956-44c3-4ec4-9c20-ecfcf28a9ca3"),
                            InvoiceId = new Guid("de4e73b3-07cb-4c11-a09d-804c2f66db38"),
                            PaymentAmount = 1000.00m,
                            PaymentDate = new DateTime(2025, 6, 2, 1, 41, 13, 234, DateTimeKind.Utc).AddTicks(3935),
                            PaymentType = "CreditCard"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("d00a14cf-2201-4bbf-a041-2e9f6d9fa8cf"),
                            Description = "A robot that cleans your house.",
                            ProductName = "Robot Cleaner"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = new Guid("9be6f733-87cd-4d7b-80b2-5a34419d5e57"),
                            Description = "A service that cleans your house.",
                            ServiceName = "Cleaning Service"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Payments", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Service", "Service")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Payments", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("InvoiceServices");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Service", b =>
                {
                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
