// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanTechInvoicing.Data;

#nullable disable

namespace UrbanTechInvoicing.Migrations
{
    [DbContext(typeof(UrbanTechDbContext))]
    [Migration("20250521005111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanTechInvoicing.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("a7d602d6-f325-43ac-ab22-6e7cf23ce852"),
                            EmailAddress = "customer1@email.com",
                            Name = "Robots Inc",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId1");

                    b.HasIndex("CustomerId2");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ServiceId1");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("4e25a828-9639-4109-a226-11611e780f3d"),
                            DueDate = new DateTime(2025, 6, 19, 19, 51, 10, 454, DateTimeKind.Local).AddTicks(5089),
                            InvoiceDate = new DateTime(2025, 5, 20, 19, 51, 10, 454, DateTimeKind.Local).AddTicks(5053),
                            InvoiceNumber = "INV001",
                            InvoiceTotal = 1000.00m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InvoiceServices");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("82e8cb71-a636-4003-903a-8de4fc0fab95"),
                            PaymentAmount = 1000.00m,
                            PaymentDate = new DateTime(2025, 5, 20, 19, 51, 10, 454, DateTimeKind.Local).AddTicks(5255),
                            PaymentType = 4
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("c384ee28-8304-42f2-bcae-95c7cefb24b3"),
                            Description = "A robot that cleans your house.",
                            ProductName = "Robot Cleaner"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = new Guid("88ee4aac-bcf3-47c1-b624-8b0705fffbb4"),
                            Description = "A service that cleans your house.",
                            ServiceName = "Cleaning Service"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1");

                    b.HasOne("UrbanTechInvoicing.Models.Customer", "CustomerId")
                        .WithMany()
                        .HasForeignKey("CustomerId2");

                    b.HasOne("UrbanTechInvoicing.Models.Product", "ProductId")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.HasOne("UrbanTechInvoicing.Models.Service", "ServiceId")
                        .WithMany()
                        .HasForeignKey("ServiceId1");

                    b.Navigation("Customer");

                    b.Navigation("CustomerId");

                    b.Navigation("ProductId");

                    b.Navigation("ServiceId");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Payments", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
