// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanTechInvoicing.Data;

#nullable disable

namespace UrbanTechInvoicing.Migrations
{
    [DbContext(typeof(UrbanTechDbContext))]
    [Migration("20250520023729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanTechInvoicing.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("0a670877-cebc-42d8-9b0d-448881b712a7"),
                            EmailAddress = "customer1@email.com",
                            Name = "Robots Inc",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId2")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProductId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId1");

                    b.HasIndex("CustomerId2");

                    b.HasIndex("ProductId1");

                    b.HasIndex("ServiceId1");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("be359938-c0cb-4b6d-9dd1-d1063ec8f9b2"),
                            DueDate = new DateTime(2025, 6, 18, 21, 37, 28, 106, DateTimeKind.Local).AddTicks(423),
                            InvoiceDate = new DateTime(2025, 5, 19, 21, 37, 28, 106, DateTimeKind.Local).AddTicks(382),
                            InvoiceNumber = "INV001",
                            InvoiceTotal = 1000.00m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InvoiceServices");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("662df25e-8b4f-48ca-8c22-aec36d753b08"),
                            PaymentAmount = 1000.00m,
                            PaymentDate = new DateTime(2025, 5, 19, 21, 37, 28, 106, DateTimeKind.Local).AddTicks(705),
                            PaymentType = 4
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a7aa384c-7c93-4aa9-87cf-11de353a2121"),
                            Description = "A robot that cleans your house.",
                            ProductName = "Robot Cleaner"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = new Guid("77c610ee-f38c-4967-a5fc-57fb49332398"),
                            Description = "A service that cleans your house.",
                            ServiceName = "Cleaning Service"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId1");

                    b.HasOne("UrbanTechInvoicing.Models.Customer", "CustomerId")
                        .WithMany()
                        .HasForeignKey("CustomerId2");

                    b.HasOne("UrbanTechInvoicing.Models.Product", "ProductId")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.HasOne("UrbanTechInvoicing.Models.Service", "ServiceId")
                        .WithMany()
                        .HasForeignKey("ServiceId1");

                    b.Navigation("Customer");

                    b.Navigation("CustomerId");

                    b.Navigation("ProductId");

                    b.Navigation("ServiceId");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Payments", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
