// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanTechInvoicing.Data;

#nullable disable

namespace UrbanTechInvoicing.Migrations
{
    [DbContext(typeof(UrbanTechDbContext))]
    [Migration("20250524211328_FixInvoiceModelForJoinTables")]
    partial class FixInvoiceModelForJoinTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanTechInvoicing.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("edb8c5bb-3be4-4c21-b521-6f02d6bf0f2c"),
                            EmailAddress = "customer1@email.com",
                            Name = "Robots Inc",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InvoiceTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = new Guid("475f410b-1da9-43b5-aad5-6a44147f9d6d"),
                            DueDate = new DateTime(2025, 6, 23, 21, 13, 27, 25, DateTimeKind.Utc).AddTicks(9896),
                            InvoiceDate = new DateTime(2025, 5, 24, 21, 13, 27, 25, DateTimeKind.Utc).AddTicks(9894),
                            InvoiceNumber = "INV001",
                            InvoiceTotal = 1000.00m,
                            Status = 1
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "PaymentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("InvoicePayments");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceProducts");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvoiceQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceLineAmount")
                        .HasColumnType("numeric");

                    b.HasKey("InvoiceId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("InvoiceServices");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Payments", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = new Guid("e819cb00-0074-4adc-9d9c-d08531259263"),
                            PaymentAmount = 1000.00m,
                            PaymentDate = new DateTime(2025, 5, 24, 21, 13, 27, 26, DateTimeKind.Utc).AddTicks(142),
                            PaymentType = "PayPal"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("adcb50f8-d9d8-4f5d-b1a4-4d8b607bb4d0"),
                            Description = "A robot that cleans your house.",
                            ProductName = "Robot Cleaner"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Service", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = new Guid("6458395e-5c2e-418e-b601-d9996e12a0a6"),
                            Description = "A service that cleans your house.",
                            ServiceName = "Cleaning Service"
                        });
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoicePayments", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Payments", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceProduct", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceProducts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.InvoiceService", b =>
                {
                    b.HasOne("UrbanTechInvoicing.Models.Invoice", "Invoice")
                        .WithMany("InvoiceServices")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanTechInvoicing.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("UrbanTechInvoicing.Models.Invoice", b =>
                {
                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceProducts");

                    b.Navigation("InvoiceServices");
                });
#pragma warning restore 612, 618
        }
    }
}
